#!/usr/bin/env bash

unset _RDK_FLAVOR
export RDK_BSP_LAYER=meta-rdk-bsp-amlogic
TOP_DIR=$(pwd)

if [ -d $TOP_DIR/meta-cmf ] && [ -z "$(echo $MACHINE | grep -- -rdk-broadband)" ]; then
    # add RDK WPE targets to conf file
    # this step has to be added before calling meta-cmf/setup-environment
    # so that the target is displayed to the user
    if [ $(grep -c 'rdk-generic-mediaclient-wpe-image' $TOP_DIR/meta-rdk/conf/conf-notes.txt) -eq 0 ]; then
        sed -i -e "/rdk-generic-mediaclient-image/a \ \ \ \ rdk-generic-mediaclient-wpe-image" $TOP_DIR/meta-rdk/conf/conf-notes.txt
    fi
    if [ $(grep -c 'rdk-generic-mediaclient-westeros-wpe-image' $TOP_DIR/meta-rdk/conf/conf-notes.txt) -eq 0 ]; then
        sed -i -e "/rdk-generic-mediaclient-wpe-image/a \ \ \ \ rdk-generic-mediaclient-westeros-wpe-image" $TOP_DIR/meta-rdk/conf/conf-notes.txt
    fi
    if [ $(grep -c 'rdk-generic-hybrid-wpe-image' $TOP_DIR/meta-rdk/conf/conf-notes.txt) -eq 0 ]; then
        sed -i -e "/rdk-generic-hybrid-image/a \ \ \ \ rdk-generic-hybrid-wpe-image" $TOP_DIR/meta-rdk/conf/conf-notes.txt
    fi
    if [ $(grep -c 'rdk-generic-hybrid-wpe-lxc-image' $TOP_DIR/meta-rdk/conf/conf-notes.txt) -eq 0 ]; then
        sed -i -e "/rdk-generic-hybrid-wpe-image/a \ \ \ \ rdk-generic-hybrid-wpe-lxc-image" $TOP_DIR/meta-rdk/conf/conf-notes.txt
    fi
    if [ $(grep -c 'rdk-generic-hybrid-westeros-wpe-image' $TOP_DIR/meta-rdk/conf/conf-notes.txt) -eq 0 ]; then
        sed -i -e "/rdk-generic-hybrid-wpe-image/a \ \ \ \ rdk-generic-hybrid-westeros-wpe-image" $TOP_DIR/meta-rdk/conf/conf-notes.txt
    fi

    if [ $(grep -c 'rdk-generic-hybrid-thunder-image' $TOP_DIR/meta-rdk/conf/conf-notes.txt) -eq 0 ]; then
        sed -i -e "/rdk-generic-hybrid-wpe-image/a \ \ \ \ rdk-generic-hybrid-thunder-image" $TOP_DIR/meta-rdk/conf/conf-notes.txt
    fi
fi

source meta-cmf/setup-environment $1
if [ $? -ne 0 ]; then
    return 1
fi

#BUILD_DIR=$(pwd)

if [ -z "$_RDK_FLAVOR" ]; then
    if [[ -z $(grep 'rdkv' conf/local.conf) ]]
    then
        _RDK_FLAVOR="rdkb"
    else
        _RDK_FLAVOR="rdkv"
    fi
fi

if [ "${_RDK_FLAVOR}" = "rdkv" ]
then
    if [[ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-wpe') -eq 0 ]] && [[ -d  ../meta-wpe ]]
    then
        cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-wpe"
EOF
    fi
fi


# Add meta-rdk-bsp-amlogic only if not already present.
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-rdk-bsp-amlogic[^-]') -eq 0 ]; then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-rdk-bsp-amlogic"
EOF
fi

# Add meta-meson only if a machine configuration choosed from different layer
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-meson[^-]') -eq 0 ]; then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-meson"
EOF
fi

# Add meta-rdk-amazon only if a machine configuration choosed from different layer
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-rdk-amazon[^-]') -eq 0  ]; then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-rdk-amazon"
EOF
fi

# Add meta-openembedded/meta-initramfs only if a machine configuration choosed from different layer
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-openembedded/meta-initramfs[^-]') -eq 0 ]; then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-openembedded/meta-initramfs"
EOF
fi
cat >> conf/local.conf <<EOF
LICENSE_FLAGS_WHITELIST="commercial"
EOF

. $RDK_ROOT_PATH/meta-meson/scripts/setup-environment-internal

# Copy <manifest>.conf file to auto.conf for revision lock
if [ -L ${BUILD_DIR}/../.repo/manifest.xml ] ; then
  MANIFEST="$(basename `readlink -f ${BUILD_DIR}/../.repo/manifest.xml ` | cut -d '.' -f 1)"
else
  MANIFEST=$(grep include ${BUILD_DIR}/../.repo/manifest.xml | cut -d '"' -f 2 | cut -d '.' -f 1)
fi
echo " Manifest Name = ${MANIFEST}"
if [ -f "${BUILD_DIR}/../.repo/manifests/${MANIFEST}.conf" ]; then
  cp ${BUILD_DIR}/../.repo/manifests/${MANIFEST}.conf ${BUILD_DIR}/conf/auto.conf
fi
